---
- name: Install Apache on Ubuntu
  hosts: ec2
  become: yes
  
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: copiar index.html del localhost
      copy:
        src: /etc/ansible/index.html
        dest: /var/www/html/
 
    - name: Start Apache service
      service:
        name: apache2
        state: started
